name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy Spring Boot App
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17

      # Step 3: Run unit tests
      - name: Unit Tests
        run: ./gradlew -b build.gradle.kts test

      # Step 4: Build the application
      - name: Build the application
        run: |
          ./gradlew clean
          ./gradlew --no-daemon build

      # Step 5: Get current date and time in IST
      - name: Get current date and time in IST
        id: vars
        run: |
          IST_DATE=$(TZ='Asia/Kolkata' date +'%Y%m%d%H%M%S')
          echo "TAG=$IST_DATE" >> $GITHUB_ENV

      # Step 6: Build Docker Image
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/githubcicd:${{ env.TAG }}

      # Step 7: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 8: Push Docker Image to Docker Hub
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/githubcicd:${{ env.TAG }}

      # Step 9: Deploy to Server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/githubcicd:${{ env.TAG }}
#            docker stop mycontainer || true
#            docker rm mycontainer || true
            docker run -d --name mycontainer -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/githubcicd:${{ env.TAG }}
        env:
          DEBUG: true